siuuu_activator:
  name: "SIUUU Challenge Activator"
  lore:
    - "&7Right-click to start the challenge"
    - "&eKill 3 mobs ih 4 minutes"
challenge:
  required-kills: 3
  timer-minutes: 4
celebration_challenge:
  timer-minutes: 2
challenge_failed_reasons:
  - "Timer-expired main challenge"
  - "Player Died"
  - "Timer-expired celebration challenge"